### ISSUE TITLE
types file for roads

### ISSUE THREAD

**Issue by dancespiele** [Dashron/roads#62]
@dashron would you include the declarations types for typescript? If you want I can do it in [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)

**Comment by Dashron** [comment]
Hey! Thanks for the interest in roads. I don't use typescript, but I'm happy to accept PRs to make it easier for anyone who does!

I recommend working off of the alpha version in master. I have a couple of minor tweaks, and a handful of unit tests left before it becomes public, but it's a stable, more robust framework.

**Comment by dancespiele** [comment]
ok then I will work in it and I will think what is the best way, or create the types definitions in this repository directly or in [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped). I have one question. Is the same way to integrate roads in express like in Koa.js?

```typescript
var road = ...; // See steps 1 and 2 for road construction
var app = express();
app.use(roads.integrations.express(road));
app.listen(8080);
```

**Comment by Dashron** [comment]
Unfortunately I only have a koa integration right now (https://github.com/Dashron/roads/blob/master/src/integrations/koa.js). At the time of writing the first version of node generators & promises were so new that I was running into weirdness with express.

I might have time to hack together an express version of the koa integration tonight.

You can also use this http server: https://github.com/Dashron/roads/blob/master/src/httpServer.js and bypass express entirely. Here's an example.

```js
let roads = require('roads');
let road = ...; // See steps 1 and 2 for road construction
let server = new roads.Server(road);
server.listen(8080);
```

**Comment by dancespiele** [comment]
Ok I see that there is intention to integrate in express 👍

**Comment by Dashron** [comment]
I just pushed up an untested express integration to the latest alpha: https://github.com/Dashron/roads/blob/master/src/integrations/express.js.

it's **very** untested, but I grabbed all the right variable names, and it compiles haha. 

I'll be taking the latest version out of alpha once I figure out what is wrong with the browserify pjax build, and write up a test for this new express integration.

It should work like your example above,

```js
app.use(roads.integrations.express(road));
```

**Comment by dancespiele** [comment]
Ok cool @Dashron. I'm working with the types such as you can see here https://github.com/dancespiele/roads/blob/types/index.d.ts . I don't know if you are interesting in some docs generator , I can prepare typedocs such as I do in my projects (ex. https://github.com/spieljs/spiel-client).

**Comment by dancespiele** [comment]
Please I need that you specify what arguments in every methods are require and what optional

**Comment by Dashron** [comment]
Do you have a preferred way for me to do that? I would love to just annotate the code if that works for you.

**Comment by dancespiele** [comment]
I don't have preferred way. It is fine for me that you annotate the code

**Comment by Dashron** [comment]
I just pushed up full jsdoc compatibility. optional params have their name wrapped in brackets, eg: https://github.com/Dashron/roads/blob/master/src/road.js#L78

**Comment by dancespiele** [comment]
About this issues I have already created a PR https://github.com/Dashron/roads/pull/63. It includes all the types for typescript.

**Comment by dancespiele** [comment]
I'm thinking in put the types in https://github.com/DefinitelyTyped/DefinitelyTyped because of this I close the pull request. I think that could be more cleaner for this project

**Comment by Dashron** [comment]
:+1: sounds great.

**Comment by dancespiele** [comment]
I made a PR already, I need that they approve it https://github.com/DefinitelyTyped/DefinitelyTyped/pull/23832

**Comment by dancespiele** [comment]
Finally the types is merged and available to use and it works :) https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/roads
