### ISSUE TITLE
The docs is mixing for cookies

### ISSUE THREAD

**Issue by dancespiele** [Dashron/roads#65]
It would be nice to add docs for cookies https://github.com/Dashron/roads/blob/master/src/middleware/cookie.js in the Readme file.
And also is mixing some method to remove the cookies https://github.com/js-cookie/js-cookie#cookie-attributes

**Comment by Dashron** [comment]
I'll add some docs. 

To remove a cookie, you set the value to `null`. I'll make sure that's in the docs!

**Comment by Dashron** [comment]
Added some cookie docs: https://github.com/Dashron/roads/blob/master/README.md#cookie.

Let me know if you have any problems with them.

**Comment by dancespiele** [comment]
what about the get

```javascript
this.Response.prototype.getCookies = function () {
			return this._cookie_values;
		};

return next();
```

**Comment by Dashron** [comment]
It's public because it's necessary for people to write a server wrapper, but I haven't documented it because I don't think it should be used outside of that one specific, random purpose. I have mixed thoughts on how I want to include it in the readme and can add it once I figure that out.

**Comment by dancespiele** [comment]
I saw that It was included in the documentation therefore I close this ticket
