### ISSUE TITLE
Issue with the response in the version 5.0.0-alpha.14

### ISSUE THREAD

**Issue by dancespiele** [Dashron/roads#66]
The version 5.0.0-alpha.14 the response doesn't work fine. When I get the JSON format it responds me like this:
{"id":5,"name":"Pepe","permission":"user"}
instead of this
{ id: 5, name: 'Pepe', permission: 'user' }
then it force me to use a every respond JSON.parse
It doesn't happens in the prior version (5.0.0-alpha.13)

**Comment by Dashron** [comment]
Is this from the request body you receive in your route, or the data returned from `road.request`?

If it's from the request body, .14 stopped parsing that in the framework, and now requires you to add the body parser middleware: https://github.com/Dashron/roads#parsebody

**Comment by dancespiele** [comment]
The respond from some request different to road.request (to use road request is required uses the same road that it was setting for the routers, it is not possible to use independently). But also although I put before of all the rest middlewares `road.use(roads.middleware.parseBody)` I have the same problem.

**Comment by Dashron** [comment]
Cool then I probably broke it :( Sorry! I'll jump on that tonight or tomorrow night, depending on available time.

**Comment by Dashron** [comment]
and note to self: ADD TESTS FOR THIS haha. I'm surprised I don't have coverage for this already

**Comment by Dashron** [comment]
How are you returning that JSON from your route? At first glance it looks like I do have some tests that should ensure if you return JSON from a route, the request will return a route.

e.g. https://github.com/Dashron/roads/blob/master/tests/tests/road/testRoadRequest.js#L146-L168

Any additional examples you can provide will help me debug this. Thanks!

**Comment by dancespiele** [comment]
```typescript
const options = {
            body: {
                id: 5,
                name: "Pepe",
                permission: "user",
            },
            json: true,
            method: "POST",
            uri: "http://localhost:3000/user",
        };
        const response: any = await rp(options);
```
it responses like this:
{"id":5,"name":"Pepe","permission":"user"}
instead of this:
{ id: 5, name: 'Pepe', permission: 'user' }

**Comment by Dashron** [comment]
ahhh, interesting. It looks like request-promise is returning a string instead of an object?

My guess is request-promise only returns an object if the response's content-type header is properly set. Can you log out the response headers and see if you can find "content-type: application/json"?

If there is, let me know, and let me know the `typeof` the JSON response you are receiving to double check you are now getting a string.

If there is not a content-type header, that logic is set outside of roads and inside the server mapping. roads-server handles this here: https://github.com/Dashron/roads-server/blob/master/src/httpServer.js#L89.

I just tested one of my websites with roads .13 and .14, both with roads-server and they both send the proper application/json content-type response header.

Again, if you don't have the proper content-type header as mentioned earlier, try replacing the _sendResponse function in roads-server's httpServer.js with the following and tell me what logs you receive for each of the failed tests.

```js
	_sendResponse (http_response, response) {
		console.log('headers q', typeof(response.headers['content-type']) !== "string");
		console.log('body q', typeof(response.body));
		// wrap up and write the response to the server
		if (typeof(response.headers['content-type']) !== "string" && typeof(response.body) === "object") {
			response.headers['content-type'] = 'application/json';
		}
		console.log('headers2', response.headers);
		http_response.writeHead(response.status, response.headers);
		
		if (response.body === null) {
			return;
		}	
		else if (typeof(response.body) === "object") {
			http_response.write(JSON.stringify(response.body));
		} else if (response.body !== undefined) {
			http_response.write(response.body);
		}

		http_response.end();
	}
```

Ideally both `headers q` and `body q` will be true, and headers2 will have a content-type key of "application/json". If `headers q` is not true, it means you are setting your own content type header instead of application/json. If `body q` is not true, it means you are returning a string out of roads, instead of an object for the server to parse into json.

**Comment by dancespiele** [comment]
It response with this head:
```json
{ 'content-type': 'application/json',                                                                                           
        date: 'Fri, 02 Mar 2018 16:24:34 GMT',                                                                                        
        connection: 'close',                                                                                                          
        'transfer-encoding': 'chunked' 
} }
```
when I receive the response the request post is the unique which I receive as string, the rest is right:
```javascript
[ { id: 1, name: 'Millie', permission: 'root' },                                                                                   
     { id: 2, name: 'Parras', permission: 'user' },                                                                                   
     { id: 3, name: 'Narges', permission: 'admin' },                                                                                  
     { id: 4, name: 'Lola', permission: 'user' },                                                                                     
     '{"id":5,"name":"Pepe","permission":"user"}' ]
```
When I run typeof response[4] I get a string as type
this is only happend with the new alpha version.

**Comment by Dashron** [comment]
Yeah it looks like it's not setting the content-type header properly. Let me know when you are able to run the rest of the tests!

We just need to figure out why that content-type header is not being set.

**Comment by dancespiele** [comment]
the test result is like this:
```
headers q true
body q object
headers2 { 'content-type': 'application/json' }
```

**Comment by Dashron** [comment]
Hmmm those logs look fine. Maybe something after that is stripping out the content type header? Are you able to builder a smaller, more isolated example that fails?

I tried a couple more ideas and have been unable to replicate this.

**Comment by Dashron** [comment]
Hey @dancespiele ,

I did more digging and found this: https://github.com/request/request-promise/issues/24
It sounds like request-promise shouldn't have ever returned an object.

Additionally I used this test script and didn't see any difference between .13 and .14. Let me know if you see any differences, or if my script is missing something important!

```js
"use strict";

let rp = require('request-promise');
require('request-debug')(rp);
let roads = require('roads');
var Server = require('roads-server').Server;

var road = new roads.Road();
let router = new roads.middleware.SimpleRouter(road);

router.addRoute('GET', '/test', function () {
    return new this.Response({'stuff': 'yeah'}, 200);
});

let server = new Server(road, function (err) {
	console.log(err.stack);
	
	switch (err.code) {
		case 404:
			return new roads.Response('Not Found', 404);
		case 405:
			return new roads.Response('Not Allowed', 405);
		default:
		case 500:
			return new roads.Response('Unknown Error', 500);
	}
});

server.listen(8085, () => {
    console.log('listening');
});


rp({uri: "http://localhost:8085/test"})
.then(function (response) {
    console.log(arguments);
    console.log('response', typeof(response));
});
```

**Comment by dancespiele** [comment]
I will try to create something simple that you can see the issue

**Comment by dancespiele** [comment]
I make a simple example here https://github.com/dancespiele/roads-test which you can reproduce the error
To run is:
* `npm install`
* `npm test`

**Comment by dancespiele** [comment]
With the example that I wrote above you will see that with the roads 14 alpha version the test fail and it shows by console this `{"id":5,"name":"Pepe","permission":"user"}`. And if you install the roads version 13 and remove the line `app.use(roads.middleware.parseBody);` the test will past correctly.

**Comment by Dashron** [comment]
ahh see the issue. The body parameter does not become parsed when you use the parseBody middleware. You have to check the request context via `this.body`. 

You can see an example here: https://github.com/Dashron/roads/blob/master/README.md#parsebody

**Comment by Dashron** [comment]
Another note, arrow functions don't work with request context.

`road.use(() => {// no context })`

`road.use(function () {// working context })`

**Comment by dancespiele** [comment]
I understand now it. But I thing that before was better in my opinion. You could also add an argument to road if the developers want to use parsebody or not and it set to true by default instead of this. With the new feature the developer cannot use arrow functions and also have to guess that if they want to use parseBody they have to handle this.body instead of body which is the argument that receive and it makes confusing and also it makes your framework less flexible.

**Comment by dancespiele** [comment]
First time I didn't like to have the parse body into the `this` but now I change my opinion therefore I close this ticket

**Comment by Dashron** [comment]
Sounds good. I have mixed thoughts, and went the "easy to build" route for now.

The main concerns are
- how to provide access to the unpased string
- should args be immutable, and consistent for every middleware function, or changable. 

Immutable felt like a safer option for now.
