### ISSUE TITLE
Warning node message without use http2

### ISSUE THREAD

**Issue by dancespiele** [Dashron/roads#70]
I'm not using http2 and by console node show me always this message
`(node:4046) ExperimentalWarning: The http2 module is an experimental API.`

**Comment by Dashron** [comment]
Yeah if you load up roads-server it pulls in http2. Just pulling in http2 logs that warning.

Your code won't use http2 unless you use roads-server's http2 object. 

I can tweak this so the message shows up later, but it's low priority right now.

**Comment by Dashron** [comment]
This is technically a roads server issue, so I'm going to close this
